#pod-red.yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  labels:
    app: web
spec:
  containers:
    - name: simple-webapp-color-red
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 80
      env:
        - name: APP_COLOR
          value: red
